chatA:chatA.c showChatA.c showChatB.c chatB.c
	gcc showChatA.c -o showChatA
	gcc showChatB.c -o showChatB
	gcc chatA.c -o chatA
	gcc chatB.c -o chatB
.PHONY:clean
clean:
	rm showChatA showChatB chatA chatB
